### ISSUE TITLE
Using a URL for a Link Card when there's a large image in the meta tags results in error

### ISSUE THREAD

**Issue by PDelahanty** [williamsdb/php2Bluesky#1]
Making a Link Card using a URL which has a large image in the meta tags results in an error response such as the following:
`BlobTooLarge`
`This file is too large. It is 1.5MB but the maximum size is 976.56KB.`

Example URL with an image that is too large and results in the error: https://twit.tv/shows/this-week-in-google/episodes/743

**Comment by williamsdb** [comment]
Is 976.56KB really the largest file size Bluesky can cope with?! I guess that there are two ways I could deal with this:

1. test for the file size and reject if it is greater than 976.56KB
2. downsample the file to get it to be less than 976.56KB but that could take some doing

I'll have a think about how to handle this and update accordingly.

**Comment by williamsdb** [comment]
I have changed the upload_media_to_bluesky function to now attempt to downsample a provided file to get it under the 1MB limit. It does this using the same method Bluesky use themselves and that's to reduce the quality by 10% each attempt until the size gets below the 1MB. Tested successfully on https://twit.tv/shows/this-week-in-google/episodes/743.

The consequences of this change are as follows:

- all files sent to Bluesky will now be JPEG irrespective of the input type. Therefore, passing an animated GIF will have interesting results!
- the change uses PHP's built-in image handling functions which rely on GD and so that is now a dependency
- when carrying out the downsample there needs to be somewhere to stick the temporary files. This is now a third parameter to upload_media_to_bluesky ($fileUploadDir) and if you omit it the code will attempt to use /tmp.

I also realise that it is possible to pass anything to upload_media_to_bluesky, such as a PDF for example and that really should be trapped in the code. I'll update for that at some point.

I'll add a new blog post over the next couple of days to document changes.

**Comment by PDelahanty** [comment]
> * all files sent to Bluesky will now be JPEG irrespective of the input type. Therefore, passing an animated GIF will have interesting results!

A PDF as the preview image would be incredibly dumb, but yeah it's probably good to have it watch out for other people's dumb mistakes.  Having said that, someone who uses an animated GIF as their preview image deserves whatever they get.  😅
